server.port=8081

spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
spring.data.redis.repositories.enabled=false

# GROQ (modelo generativo)
spring.ai.model.chat=openai
spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=openai/gpt-oss-20b
spring.ai.openai.chat.options.temperature=0.2

# EMBEDDINGS LOCALES (Transformers ONNX)
spring.ai.model.embedding=transformers
spring.ai.embedding.transformer.tokenizer.uri=https://huggingface.co/intfloat/e5-small-v2/raw/main/tokenizer.json
spring.ai.embedding.transformer.onnx.model-uri=https://huggingface.co/intfloat/e5-small-v2/resolve/main/model.onnx
spring.ai.embedding.transformer.tokenizer.options.padding=true

# H2 (solo para historial RAG)
spring.datasource.url=jdbc:h2:file:./data/thriftydb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console