
spring.redis.host=localhost
spring.redis.port=6379
server.port=8081

spring.data.redis.repositories.enabled=false


spring.data.mongodb.uri=mongodb+srv://Serverus1324:Serverus1324@cluster0.ohth4tm.mongodb.net/CalcGastosU?retryWrites=true&w=majority&appName=Cluster0
